# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ocloud < Formula
  desc "Tool for finding and connecting to OCI instances"
  homepage "https://github.com/cnopslabs/ocloud"
  version "0.0.15"
  license "MIT"

  on_macos do
    url "https://github.com/cnopslabs/ocloud/releases/download/v0.0.15/ocloud_0.0.15_darwin_all.tar.gz"
    sha256 "4aacad1176a0a10f5b7bff63d05cead3e3ba5dd171a51a61581ce39c169f1566"

    def install
      bin.install "ocloud"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/cnopslabs/ocloud/releases/download/v0.0.15/ocloud_0.0.15_linux_amd64.tar.gz"
      sha256 "4e4692e625279c31d12f5d41a9179130b5fae92ed5042186bd715b524da750ea"
      def install
        bin.install "ocloud"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/cnopslabs/ocloud/releases/download/v0.0.15/ocloud_0.0.15_linux_arm64.tar.gz"
      sha256 "5de554c3609d1029298681653b1d1f41fdfdf67edd54de03ba28c229871f08d3"
      def install
        bin.install "ocloud"
      end
    end
  end
end
