# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ocloud < Formula
  desc "Tool for finding and connecting to OCI instances"
  homepage "https://github.com/cnopslabs/ocloud"
  version "0.1.6"
  license "MIT"

  on_macos do
    url "https://github.com/cnopslabs/ocloud/releases/download/v0.1.6/ocloud_0.1.6_darwin_all.tar.gz"
    sha256 "b4fa2c8dce2e193328039689aa365e6bdab55442679196cfdd3ff81c706df58f"

    def install
      bin.install "ocloud"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cnopslabs/ocloud/releases/download/v0.1.6/ocloud_0.1.6_linux_amd64.tar.gz"
      sha256 "cbf0c27cee15a5f80ef09946d9751dca72317140beace2ef4d518ac2172667ef"
      def install
        bin.install "ocloud"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cnopslabs/ocloud/releases/download/v0.1.6/ocloud_0.1.6_linux_arm64.tar.gz"
      sha256 "2d8b5292746da03d4fa90e9c68fe0eb8baf46bcd25fcbf3de3f34c1064c8617b"
      def install
        bin.install "ocloud"
      end
    end
  end
end
